export const APPLICATION_SET              = 'APPLICATION_SET'
export const APPLICATION_IS_FETCHING_SET  = 'APPLICATION_IS_FETCHING_SET'
export const APPLICATION_ERROR_SET        = 'APPLICATION_ERROR_SET'